### ISSUE TITLE
I am stuck in the onboarding screen after I input the email and my name.

### ISSUE THREAD

**Issue by JonathanSum** [fabio-rosati/little-lemon#1]

**Comment by JonathanSum** [comment]
![Screenshot_20230210-175844](https://user-images.githubusercontent.com/21982975/218233232-1e9c5f62-00c6-4540-8546-e227ba888f82.jpg)

**Comment by fabio-rosati** [comment]
Hello Jonathan! As for the project requirements, the name must only accept letters. Remove the number 1 from the name and the button will be enabled.

**Comment by JonathanSum** [comment]
> 

I don't see it. I only see it said:
...the Onboarding screen feature a Next button that is only enabled when the details are entered?

**Comment by fabio-rosati** [comment]
![image](https://user-images.githubusercontent.com/124038456/218252970-d1da2eb8-414f-4407-a2d2-3b045df752c5.png)

Maybe I misunderstood what they meant with "string characters", but it made sense to me that a first name couldnìt contain any number nor special character.

**Comment by JonathanSum** [comment]
![image](https://user-images.githubusercontent.com/21982975/218265340-7174e011-d71d-46eb-93fe-be9c7ddd9516.png)

**Comment by fabio-rosati** [comment]
Well, I guess thay couldn't login neither...

![image](https://user-images.githubusercontent.com/124038456/218305202-691f0a88-0b84-414d-ad2f-461f89c7a05c.png)

I fixed the issue with a new commit.
